"""Add allowed_roles to core models

Revision ID: 15b32dfc3e54
Revises: 
Create Date: 2026-07-29 20:16:49.991066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15b32dfc3e54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('agents', sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('guardrails', sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llms', sa.Column('allowed_roles', sa.JSON(), nullable=True))
    op.add_column('mcps', sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcps', 'allowed_roles')
    op.drop_column('llms', 'allowed_roles')
    op.drop_column('guardrails', 'allowed_roles')
    op.drop_column('agents', 'allowed_roles')

    # ### end Alembic commands ###
