"""standardize_visibility_controls

Revision ID: 3ad28b940015
Revises: c9c08d414021
Create Date: 2026-07-29 20:50:43.117050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ad28b940015'
down_revision: Union[str, Sequence[str], None] = 'c9c08d414021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardrails', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('guardrails', sa.Column('creator_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'guardrails', 'users', ['creator_id'], ['id'])
    op.add_column('tools', sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'allowed_roles')
    op.drop_constraint(None, 'guardrails', type_='foreignkey')
    op.drop_column('guardrails', 'creator_id')
    op.drop_column('guardrails', 'is_public')
    # ### end Alembic commands ###
