"""add_is_public_to_agents_and_llms

Revision ID: c9c08d414021
Revises: 15b32dfc3e54
Create Date: 2026-07-29 20:36:03.299938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9c08d414021'
down_revision: Union[str, Sequence[str], None] = '15b32dfc3e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('llms', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llms', 'is_public')
    op.drop_column('agents', 'is_public')
    # ### end Alembic commands ###
